name: Desplegar sitio web en InfinityFree

on:
  push:
    branches:
      - master # Rama principal del despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código más reciente
        uses: actions/checkout@v4

      - name: Sincronizar archivos vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/ # Directorio en el servidor donde se desplegarán los archivos
          exclude: |
            LICENSE
            README.md
